defmodule BillBored.Topics do
  @moduledoc """
  Context for consume topic generated by openai and stored in db.
  """

  alias BillBored.Topics.Topic
  alias Repo

  def get_topics do
    Repo.one(Topic)
  end

  def get_topics! do
    Repo.one!(Topic)
  end

  def create_topic(meta) do
    %Topic{}
    |> Topic.changeset(meta)
    |> Repo.insert()
  end

  def topic_changeset(%Topic{} = topic, meta \\ []) do
    Topic.changeset(topic, meta)
  end
end
